apiVersion: apps/v1
kind: Deployment
metadata:
  name: das-backend
spec:
  selector:
    matchLabels:
      app: das-backend
  template:
    metadata:
      labels:
        app: das-backend
    spec:
      containers:
        - name: das-backend
          image: gcr.io/architect-certification-289902/20/das-backend:1
          ports:
          - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/das_db"
            - name: GOOGLE_CLOUD_PROJECT
              value: architect-certification-289902
          resources:
            requests:
              cpu: 500m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: das-backend
spec:
  type: ClusterIP
  selector:
    app: das-backend
  ports:
  - port: 8090
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: das-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: das-backend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60