node {
  stage('========== Clone repository ==========') {
    checkout scm
  }
  stage('========== Build image ==========') {
    dir('frontend'){
        script{
            app = docker.build("sncap/das-frontend", "-f ./frontend/Dockerfile .")
        }
    }
  }
  stage('========== Push image ==========') {
    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub') {
      app.push("${env.BUILD_NUMBER}")
      app.push("latest")
    }
  }
}