version: "3"

services:
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=das_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    container_name: msa_postgres