apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: das-frontend
      context: das-frontend
    - image: das-backend
      context: das-backend
      jib:
        type: gradle
deploy:
  kubectl:
    manifests:
      - k8s/**.yaml