apiVersion: apps/v1
kind: Deployment
metadata:
  name: das-backend
spec:
  selector:
    matchLabels:
      app: das-backend
  template:
    metadata:
      labels:
        app: das-backend
    spec:
      containers:
        - name: das-backend
          image: das-backend
          ports:
          - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/das_db"
          resources:
            requests:
              cpu: 500m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: das-backend
spec:
  type: ClusterIP
  selector:
    app: das-backend
  ports:
  - port: 8090