apiVersion: apps/v1
kind: Deployment
metadata:
  name: das-backend
  labels:
    app: das-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: das-backend
  template:
    metadata:
      labels:
        app: das-backend
    spec:
      containers:
        - name: das-backend
          image: sncap/das-backend:0.1.0
          ports:
          - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://mydb-postgresql:5432/das_db"
            - name: SPRING_REDIS_HOST
              value: myredis-master
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: das-backend
spec:
  type: ClusterIP
  selector:
    app: das-backend
  ports:
  - port: 8090
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: das-backend
spec:
  scaleTargetRef:  # 스케일 아웃할 타겟 설정
    apiVersion: apps/v1
    kind: Deployment  #  스케일 아웃할 타겟의 종류 (deployment, replicaset 등)
    name: das-backend
  minReplicas: 1  # 최소 replicas 개수
  maxReplicas: 5  # 최대 replicas 개수
  metrics:
    - resource:
        name: cpu  # HPA를 구성할 리소스(CPU, MEM 등)
        targetAverageUtilization: 60  # CPU 사용률이 60% 이상일 경우 생성
      type: Resource  # 리소스 타입 선언