apiVersion: apps/v1
kind: Deployment
metadata:
  name: das-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: das-frontend
  template:
    metadata:
      labels:
        app: das-frontend
    spec:
      containers:
        - name: das-frontend
          image: sncap/das-frontend:0.0.1
          command: [ "http-server", "dist", "--proxy", "http://das-backend:8090"]
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: das-frontend
spec:
  type: ClusterIP
  selector:
    app: das-frontend
  ports:
  - port: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: das-frontend
spec:
  scaleTargetRef:  # 스케일 아웃할 타겟 설정
    apiVersion: apps/v1
    kind: Deployment  #  스케일 아웃할 타겟의 종류 (deployment, replicaset 등)
    name: das-frontend
  minReplicas: 1  # 최소 replicas 개수
  maxReplicas: 5  # 최대 replicas 개수
  metrics:
    - resource:
        name: cpu  # HPA를 구성할 리소스(CPU, MEM 등)
        targetAverageUtilization: 60  # CPU 사용률이 60% 이상일 경우 생성
      type: Resource  # 리소스 타입 선언