apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: das-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: das-frontend
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: das-backend
                port:
                  number: 8090
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: das-backend
                port:
                  number: 8090
          - path: /cds
            pathType: Prefix
            backend:
              service:
                name: das-backend
                port:
                  number: 8090
          - path: /downloadFile
            pathType: Prefix
            backend:
              service:
                name: das-backend
                port:
                  number: 8090
          - path: /api2Csv
            pathType: Prefix
            backend:
              service:
                name: das-backend
                port:
                  number: 8090